### ISSUE TITLE
Wrong path to ini file

### ISSUE THREAD

**Issue by bknowles** [mrabbitt/BGEE_Sikuli_auto_roller#1]
The actual location is more like ~/Library/Containers/com.beamdog.baldursgateenhancededition/Data/Documents/Baldur's Gate - Enhanced Edition/Baldur.ini

**Comment by mrabbitt** [comment]
Thanks.  

I hadn't noticed this before, but `~/Documents/Baldur's Gate - Enhanced Edition` seems to be a symbolic link to `~/Library/Containers/com.beamdog.baldursgateenhancededition/Data/Documents/Baldur's Gate - Enhanced Edition`.  I guess the Beamdog installer put the symlink in `~/Documents` to make it easier to access.

@bknowles, Do you see the symlink in `~/Documents` on your installation?  Also, did you install the game via the Apple AppStore, Beamdog, GOG, or some other distribution method?

**Comment by bknowles** [comment]
No, there was no symlink in my installation -- from the Apple App store.

**Comment by mrabbitt** [comment]
I updated the path in `README.md`.  Thanks!
